export default function ClientMail(props) {
    return (
        <div><p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:9pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#202124;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;👋&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Registrierungsbest&auml;tigung Open Data Bayern</span></p>'+
            +'<p dir="ltr" style="line-height:2.465;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Sehr geehrte(r) Vorname Nachname</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#3c4043;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">,</span></p>'+
            +'<p dir="ltr" style="line-height:2.465;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">wir haben Ihre Registrierungsanfrage erhalten und freuen uns, dass Sie Ihre Daten auf der Open Data Bayern Plattform bereitstellen wollen.</span></p>'+
            +'<p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ihre Registrierung befindet sich derzeit in Bearbeitung und kann bis zu drei Werktage in Anspruch nehmen. Falls erforderlich, wird sich unser Team mit Ihnen in Verbindung setzen.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;_______________________________________________</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Erste Informationen zu unserer Plattform:</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ziel von Open Data Bayern</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Das Hauptziel von Open Data in Bayern ist es, zur Entwicklung der Gesellschaft und der Demokratie im Land beizutragen, durch die Bereitstellung aktueller statistischer Informationen, aus denen die Nutzer neues Wissen generieren, Gesch&auml;ftsentscheidungen treffen und den Alltag erleichtern k&ouml;nnen.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Daten, die auf dem Portal ver&ouml;ffentlicht werden k&ouml;nnen</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Offene Daten sind Verwaltungsdaten (z.B. Wetterdaten,&nbsp;</span><a href="https://www.govdata.de/web/guest/daten/-/details/hochwasser1954gebiete" style="text-decoration:none;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hochwasser</span></a><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, usw), die nicht gegen gesetzliche Bestimmungen versto&szlig;en, wie z. B. die Datenschutzrichtlinien einer Organisation, die unter&nbsp;</span><a href="https://opendatacommons.org/licenses/" style="text-decoration:none;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">einer offenen Lizenz stehen</span></a><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;und frei ver&ouml;ffentlicht werden k&ouml;nnen.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Wer kann Daten auf dem Portal ver&ouml;ffentlichen</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Jeder Mitarbeiter einer administrativen Organisation kann Daten auf dem Portal ver&ouml;ffentlichen. Zu diesem Zweck wird f&uuml;r jeden Mitarbeiter bei der Registrierung ein individueller Zugang mit einer Verkn&uuml;pfung zur Organisation angelegt. Derzeit kann ein Mitarbeiter Daten f&uuml;r eine Organisation ver&ouml;ffentlichen.&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Daten und Datenformat f&uuml;r die Ver&ouml;ffentlichung</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Um Daten in das Portal hochzuladen, erstellen Sie einen Datensatz und f&uuml;gen die f&uuml;r das Thema relevanten Dateien oder Links hinzu. F&uuml;r die Ver&ouml;ffentlichung der Daten werden alle offenen formate akzeptiert, z.B. csv, html, pdf, wms, gml, text/csv, GeoJSON, TIFF, &nbsp;GeoTIFF, KML, SHP, usw.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Datenaustausch mit GOVDATA</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Die Open Data Bayern Plattform tauscht Daten mit GOVDATA aus. Das bedeutet, dass die Daten, die Sie auf Open Data Bayern hochladen, auch auf GOVDATA &uuml;bertragen werden und der Endnutzer sie sowohl auf Open Data Bayern als auch auf GOVDATA nutzen kann.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Automatische Datenerfassung</span></p> '+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Wenn Sie als Datenanbieter Daten auf Ihrer eigenen Plattform ver&ouml;ffentlichen und diese noch nicht an GOVDATA &uuml;bermitteln, k&ouml;nnen wir eine automatische Daten&uuml;bertragung von Ihrer Plattform &uuml;ber die Open Data Bayern Plattform veranlassen. Kontaktieren Sie uns dazu unter&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">opendatabayern@stmd.bayern.de.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Erleichterung des Datenabrufs f&uuml;r den Endnutzer</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Um den Nutzern den Zugang zu Ihren Daten zu erleichtern, bitten wir Sie, klare, leicht lesbare, kurze (3-4 S&auml;tze) Beschreibungen Ihrer Daten zu erstellen und die entsprechenden Tags anzugeben.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">________________________________________________</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">F&uuml;r Fragen stehen wir gerne unter &nbsp;</span><a href="mailto:opendatabayern@stmd.bayern.de" style="text-decoration:none;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">opendatabayern@stmd.bayern.de</span></a><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">zur Verf&uuml;gung.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Beachten Sie, dass dies eine automatisch erzeugte E-Mail ist. Bitte antworten Sie nicht auf diese E-Mail.</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Viele Gr&uuml;&szlig;e</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ihr Open Data Bayern Team</span></p>'+
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:181px;height:70px;"><img src="https://lh5.googleusercontent.com/amvlLoYcHC1pOFFfrrtyJTp1ELMiDoo-Per1KDc7kxu_UwXhSWi7uOjqHaGBNj-DgMTPFVQYeBJCHGR5ieI2Nr1XaOKOI8i5xsizOYeuy-LksrbODYS5tYDiedpNg6cdhz_xd7Gq" width="181" height="70" /></span></span></p></div>'
        )
   
}