export default function SetPassMail(props) {
    return (
        <div>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:9pt;margin-bottom:0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Sehr geehrte(r) Vorname Nachname,</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">vielen Dank f&uuml;r Ihre Registrierung bei Open Data Bayern.&nbsp;</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Um den Registrierungsprozess abzuschlie&szlig;en, legen Sie bitte ein sicheres Passwort fest:&nbsp;</span><a href={props.link} style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{props.link}.</a><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#0000ff;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Anschlie&szlig;end k&ouml;nnen Sie sich mit Ihrem&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Benutzernamen</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">VorNach&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">einloggen und Daten Ihrer Organisation ver&ouml;ffentlichen.</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bei Fragen k&ouml;nnen Sie sich jederzeit gerne per E-Mail an uns wenden:&nbsp;</span><span style="font-size:11.5pt;font-family:Arial;color:#1d1c1d;background-color:#f8f8f8;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><a href="mailto:opendatabayern@stmd.bayern.de" style="text-decoration:none;"><span style="font-size:10.5pt;font-family:Arial;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">opendatabayern@stmd.bayern.de</span></a></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vielen Dank f&uuml;r Ihre Unterst&uuml;tzung und Ihren Beitrag zur Open Data Community in Bayern!</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;">&nbsp;</p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Beachten Sie, dass dies eine automatisch erzeugte E-Mail ist. Bitte antworten Sie nicht auf diese E-Mail!</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Viele Gr&uuml;&szlig;e</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ihr Open Data Bayern Team</span></p>
            <p dir="ltr" style="line-height:2.055;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:9pt 0pt 0pt 0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#172b4d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:187px;height:72px;"><img src="https://lh5.googleusercontent.com/amvlLoYcHC1pOFFfrrtyJTp1ELMiDoo-Per1KDc7kxu_UwXhSWi7uOjqHaGBNj-DgMTPFVQYeBJCHGR5ieI2Nr1XaOKOI8i5xsizOYeuy-LksrbODYS5tYDiedpNg6cdhz_xd7Gq" width="187" height="72"/></span></span></p>
        </div>
    )
}